config/routes.rb
Rails.application.routes.draw do
  get 'legal/index'
  get 'reachout/index'
  get 'about/index'
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/legal_controller.rb
class LegalController < ApplicationController
  def index
  end
end

app/controllers/reachout_controller.rb
class ReachoutController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/legal_helper.rb
module LegalHelper
end

app/helpers/reachout_helper.rb
module ReachoutHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/layouts/_footer.html.erb
<hr>
<footer style="font-color: black;">
	<div class="row">
		<div class="medium-6 columns">
			<nav aria-label="You are here:" role="navigation">
			  <ul class="breadcrumbs">
			    <li><%= link_to "Inicio", root_path %></li>
			    <li><%= link_to "Mis recetas", about_index_path %></li>
			    <li><%= link_to "Sobre mí", reachout_index_path %></li>
			  </ul>
			</nav>
		</div>
		<div class="medium-2 columns">
			<nav aria-label="You are here:" role="navigation">
			  <ul class="breadcrumbs">
			    <li><%= link_to "Legal", legal_index_path %></li>
			  </ul>
			</nav>
		</div>
		<div class="medium-4 columns">
			<nav aria-label="You are here:" role="navigation">
			  <ul class="breadcrumbs">
			    <li class="menu-text" style="text-align: right;">Copyright © 2019 WebCorp</li>
			  </ul>
			</nav>
		</div>
	</div>
	
</footer>

app/views/layouts/_foundation.html.erb
<script>
     window.onload = function(){ $(document).foundation(); };
</script>

app/views/layouts/_header.html.erb
<header>
	<br>
	<div class="row">
		<div class="small-12 medium-12 large-12 columns">
			<nav aria-label="You are here:" role="navigation">
			  	<ul class="breadcrumbs">
			    	<li style="font-family: 'Hind', sans-serif;font-color: black;"><%= link_to "Inicio", root_path %></li>
			    	<li><%= link_to "Mis recetas", about_index_path %></li>
			    	<li><%= link_to "Sobre mí", reachout_index_path %></li>
			  	</ul>
			</nav>
		</div>
	</div>
	<!--
		LARGE
	-->
	<div class="row hide-for-small-only hide-for-medium-only show-for-large">
		<div class="medium-3 columns">
		</div>
		<div class="medium-6 columns">
			<center><%= image_tag "killy3.jpg",:alt=>"gerardo", :style=>"height:95px;width:90px; border-radius: 50%;", :class=>"avatar-image"%></center>
			<h2><center>Gerardo David Bracho F.</center></h2>
		</div>
		<div class="medium-3 columns"><h2></h2></div>
	</div>
	<div class="row hide-for-small-only hide-for-medium-only show-for-large">
		<div class="medium-12 columns">
			<h4>
				<center>Chef Internacional</center>
			</h4>
		</div>
	</div>
	<!--
		MED
	-->
	<div class="row show-for-medium hide-for-small hide-for-large">
		<div class="small-2 columns"></div>
		<div class="small-2 columns">
			<%= image_tag "killy3.jpg",:alt=>"gerardo", :style=>"height:95px;width:90px; border-radius: 50%;", :class=>"avatar-image"%>
		</div>
		<div class="small-8 columns" style="text-align: left;">
			<h2>Gerardo David Bracho F. | </h2> <h4 >Chef Internacional</h4>
		</div>
	</div>
	<!--
		SMALL
	-->
	<div class="row show-for-small hide-for-medium hide-for-large">
		<div class="small-3 columns">
			<%= image_tag "killy3.jpg",:alt=>"gerardo", :style=>"height:75px;width:79px; border-radius: 50%;", :class=>"avatar-image"%>
		</div>
		<div class="small- columns" style="text-align: left;">
			<h2>Gerardo David Bracho F. | </h2> <h4 >Chef Internacional</h4>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Gerardo David Bracho F." %></title>

    <%= stylesheet_link_tag    "application" %>
    
    <link href="https://fonts.googleapis.com/css?family=Hind|Libre+Baskerville&display=swap" rel="stylesheet">
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>

  <body data-spy="scroll" data-target=".navbar" data-offset="50">

    <%= yield %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "map" %>
    <%= javascript_include_tag "smooth-scroll" %>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <%= javascript_include_tag "image-effect" %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDFZjOV0KA68G2YAh-rn7I3qKqCQEh_Ja0&callback=myMap"></script>
  </body>
</html>

app/views/legal/index.html.erb
<h1>Legal#index</h1>
<p>Find me in app/views/legal/index.html.erb</p>

app/views/reachout/index.html.erb
<div class="timeline">

  <div class="timeline-item">
    <div class="timeline-icon">
        <%= image_tag "venezuela(1).svg"%>
    </div>

    <div class="timeline-content">
      <p class="timeline-content-date">1997</h2>
      <p>Nací en Caracas, Venezuela. Viví en la Isla de Margarita toda mi vida.</p>
    </div>
  </div>

  <div class="timeline-item">
    <div class="timeline-icon">
      <%= image_tag "carnicero.svg"%>
      <br>
    </div>
    <div class="timeline-content right">
      <p class="timeline-content-date">2014-2015</h2>
      <p>Estudié un tiempo Licenciatura en Estadística pero decidí seguir mis sueños y
me retiré para dedicarme plenamente a la cocina.</p>
    </div>
  </div>

  <div class="timeline-item">
    <div class="timeline-icon">
        <%= image_tag "cocina.svg"%>
		<br>
    </div>
    <div class="timeline-content">
      <p class="timeline-content-date">2016</h2>
      <p>Estudié con el reconocido chef Sumito Estévez y trabajé en 3 cocinas.
      </p>
    </div>
  </div>

  <div class="timeline-item">
    <div class="timeline-icon">
        <%= image_tag "republica-dominicana.svg"%><br>
    </div>
    <div class="timeline-content right">
      <p class="timeline-content-date">2017</h2>
      <p>
         Este año trabajé en una cocina en la República Dominicana por 3 meses.
      </p>
    </div>
  </div>

  <div class="timeline-item">
    <div class="timeline-icon">
        <%= image_tag "chile.svg"%><br>
    </div>
    <div class="timeline-content">
      <p class="timeline-content-date"><span class="timeline-content-month">Diciembre</span> 2017 - <span class="timeline-content-month">Abril</span> 2018</p>
      <p>En Diciembre del año 2017 emigré a Chile y aquí empecé a trabajar en la cocina de Bastad Burgers en La Serena.</p>
    </div>
  </div>

  <div class="timeline-item">
    <div class="timeline-icon">
            <%= image_tag "cocina(1).svg"%><br>
    </div>
    <div class="timeline-content right">
      <p class="timeline-content-date"><span class="timeline-content-month">Abril</span> 2018 - <span class="timeline-content-month">Abril 2019</span></p>
      <p>Trabajé en Ambrosía y Pan Bar en Santiago de Chile, ambas cocinas al mismo tiempo. Tuve el privilegio de volver a estudiar y trabajar con Sumito.</p>
    </div>
  </div>

  <div class="timeline-item">
    <div class="timeline-icon">
    	<%= image_tag "cocinero.svg"%><br>
    </div>
    <div class="timeline-content">
      <p class="timeline-content-date"><span class="timeline-content-month">Actualmente</span></p>
      <p> Estoy realizando pasantías en Boragó en Santiago de Chile. Estoy en constante crecimiento y búsqueda de oportunidades donde pueda ofrecer mis servicios.</p>
    </div>
  </div>

</div>
<div class="row hide-for-small-only">
	<div class="medium-3 columns"></div>
	<div class="medium-6 columns">
		<p><i>Contáctame.</i> <br><b>Email:</b> <i>gdavidbracho@gmail.com</i> | <b>mobile:</b> <i>+5678293000</i></p>
	</div>
	<div class="medium-3 columns"></div>
</div>

<div class="row show-for-small hide-for-medium hide-for-large">
	<div class="small-12 columns"><p><i>Contáctame.</i> <br><b>Email:</b> <i>gdavidbracho@gmail.com</i> | <b>mobile:</b> <i>+5678293000</i></p></div>
</div>

app/views/welcome/index.html.erb
<div id="Welcome">
	  		<!---Start navigation Bar -->
	    	<nav class="navbar navbar-expand-lg navbar fixed-top  navbar-light bg-light">
		 		<a class="navbar-brand" href="#Welcome">
    				<%= image_tag "logo.png",:alt=>"gerardo", :style=>"height:50px;width:50px;", :class=>"d-inline-block"%>
    				Gerardo David Bracho F.
		 		</a>
		 		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
		    		<span class="navbar-toggler-icon"></span>
		 		</button>
			  	<div class="collapse navbar-collapse" id="navbarText">
			    	<ul class="navbar-nav ml-auto">
			      		<li class="nav-item">
			        		<a class="nav-link" href="#Welcome">Inicio</a>
			      		</li>
					    <li class="nav-item">
					    	<a class="nav-link" href="#Sobremi">Sobre Mi</a>
					    </li>
					    <li class="nav-item">
					    	<a class="nav-link" href="#PF">Portafolio</a>
					    </li>
					    <li class="nav-item">
					    	<a class="nav-link" href="#contacto">Contacto</a>
					    </li>
				    </ul>
				</div>
			</nav>
			<!--- End Navigation Bar -->
			<!--- Start Carousel -->
			<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
				    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
				    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
				</ol>
				<div class="carousel-inner">
					<div class="carousel-item active">
						<%= image_tag "slider1.jpg",:alt=>"gerardo", :class=>"d-block w-100 img-fluid img-slider"%>
				    	
				    	<div class="carousel-caption">
						    <h2>¡Bienvenido!</h2>
							<p>Quiero compartir con ustedes, y de la manera más próxima, mi biografía gastronómica, experiencias, creaciones, nuevos retos, etc.</p>
						</div>
				    </div>
				    <div class="carousel-item">
				    	<%= image_tag "slider2.jpg",:alt=>"gerardo", :class=>"d-block w-100 img-fluid img-slider"%>
				      	<div class="carousel-caption">
						    <h2>La cocina como pasión</h2>
							<p>Como ya saben, mi pasión es cocinar, en ese espacio de pocos metros cuadrados, es donde me invade siempre la inspiración.</p>
						</div>
				    </div>
				    <div class="carousel-item">
				    	<%= image_tag "slider3.jpg",:alt=>"gerardo", :class=>"d-block w-100 img-fluid img-slider"%>
				      	<div class="carousel-caption">
						    <h2>En la cocina</h2>
							<p>Se activan todos mis sentidos, el plato es el lienzo, la cuchara mi pincel y cada ingrediente un color con el que he llenado mi vida</p>
						</div>
				    </div>
				</div>
				<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				</a>
			</div>
		</div>
			<!--- End of Carousel -->
			<!--- Restaurant-->
		<div class="container">
		 	<div class="row" id="Sobremi">
	    		<div class="col navMenu">
	     		 	<h2 class="text-center" >Sobre Mí</h2>
	    		</div>
  			</div>
  			<div class="row bg-light" >
  				<div class="col-md-6">
  					<h3>Location</h3>
  					<p>Thanks for stopping by. We are the last authentic Italian restaurant in Milan, serving delicious Italian cuisine cooked by the best chefs. It only takes a few minutes to browse through our website and check out our menu. We hope you'll soon join us for a superb Italian culinary experience.</p>
  					<h5>A Unique Experience</h5>
  					<p>Thanks for stopping by. We are the last authentic Italian restaurant in Milan, serving delicious Italian cuisine cooked by the best chefs. It only takes a few minutes to browse through our website and check out our menu. We hope you'll soon join us for a superb Italian culinary experience.</p>
  				</div>
  				<div class="col-md-6" data-aos="fade-up">
  					<%= image_tag "location.jpg", :class=>"img-fluid"%>
  				</div>
  			</div>
  			<div class="row bg-light"><br></div>
  			<div class="row bg-light">
  				<div class="col-md-6 order-md-1 order-2" data-aos="fade-up">
  					<%= image_tag "cuisine.jpg",:class=>"img-fluid"%>

  				</div>
  				<div class="col-md-6 order-md-12 order-1">
  					<h3>Cuisine</h3>
  					<p>Thanks for stopping by. We are the last authentic Italian restaurant in Milan, serving delicious Italian cuisine cooked by the best chefs. It only takes a few minutes to browse through our website and check out our menu. We hope you'll soon join us for a superb Italian culinary experience.</p>
  					<h5>A Unique Experience</h5>
  					<p>Thanks for stopping by. We are the last authentic Italian restaurant in Milan, serving delicious Italian cuisine cooked by the best chefs. It only takes a few minutes to browse through our website and check out our menu. We hope you'll soon join us for a superb Italian culinary experience.</p>
  				</div>
  			</div>
  			<!--- End of Restaurant -->
  			<!--- Start of Menu-->
			<div class="row" id="PF">
				<div class="col navMenu">
	     		 	<h2 class="text-center" >Servicios y Portafolio</h2>
				</div>
			</div>
			<div class="row bg-light">
				<div class="col-md-4" data-aos="slide-up">
					<div class="card view zoom">
						<%= image_tag "meat-menu.jpg", :class=>"card-img-top img-fluid"%>

					  	<div class="card-body">
					  		<h5 class="card-title">~ Meat Menu ~</h5>
					    	<ul class="list-group list-group-flush">
							    <li class="list-group-item">Bocconcini di carne in nido di sfoglia</li>
							    <li class="list-group-item">Bruschette con maiale al curry</li>
							 	<li class="list-group-item">Uova al prosciutto</li>
							 	<li class="list-group-item">Vitello tonnato</li>
							 	<li class="list-group-item">Fesa di tacchino marinata con olive</li>
							</ul>
					  	</div>
					</div>
				</div>
				<div class="col-md-4" data-aos="slide-up">
					<div class="card">

				    	<%= image_tag "fish-menu.jpg",:alt=>"gerardo", :class=>"card-img-top img-fluid"%>
					  	<div class="card-body">
					  		<h5 class="card-title">~ Fish Menu ~</h5>
					    	<ul class="list-group list-group-flush">
							    <li class="list-group-item">Carpaccio di polpo</li>
							    <li class="list-group-item">Cozze al verde</li>
							 	<li class="list-group-item">Cocktail di gamberi</li>
							 	<li class="list-group-item">Risotto alla crema di scampi</li>
							 	<li class="list-group-item">Ravioli di pesce con crema di scampi</li>
							</ul>
					  	</div>
					</div>
				</div>
				<div class="col-md-4" data-aos="slide-up">
					<div class="card">
						<%= image_tag "menu-vegetarian.jpg",:alt=>"gerardo", :class=>"card-img-top img-fluid"%>
					  	<div class="card-body">
					  		<h5 class="card-title">~ Vegetarian Menu ~</h5>
					    	<ul class="list-group list-group-flush">
							    <li class="list-group-item">Parmigiana di melanzane</li>
							    <li class="list-group-item">Strudel con ricotta e spinaci</li>
							 	<li class="list-group-item">Polpette di spinaci e ricotta</li>
							 	<li class="list-group-item">Frittata di patate al forno</li>
							 	<li class="list-group-item">Spaghetti con le polpettine vegetariane</li>
							</ul>
					  	</div>
					</div>
				</div>
			</div>
			<!--- End of Menu -->
			<!--- Start of Reservation-->
			<div class="row" id="contacto">
				<div class="col navMenu">
	     		 	<h2 class="text-center">Contacto</h2>
				</div>
			</div>
			<div class="row">
				<div class=" col-lg-12 reserve-container" data-aos="fade-up">
					
					<%= image_tag "reserve.jpg",:alt=>"gerardo", :class=>"img-fluid image-reserve"%>

					<div class="reserve-text col-lg-12 ">
						<h1 class="text-center">Timetables</h1>
						<div class="row">
							<div class="col-6">
							   	<h2 class="text-center">Lunch</h2>
							    <h5 class="text-center">12:00 - 15:00</h5>
							</div>
							<div class="col-6">
							    <h2 class="text-center">Dinner</h2>
							    <h5 class="text-center">19:30 - 23:30</h5>
							</div>
						</div>
					</div>
				</div>
			</div>
			<br>
			<div class="row bg-light">
				<div class="col">
					<form>
						<div class="form-row">
						  	<div class="form-group col-6">
						  		<h3>Reserve</h3>
						  		<label for="inputDate"> Date</label>
						  		<input type="date" class="form-control" id="inputDate" placeholder="Data gg/mm/aaaa">
						  	</div>
						  	<div class="form-group col-6">
						  		<h3>Details</h3>
						  		<label for="inputName"> Name</label>
						  		<input type="text" class="form-control" id="inputName" placeholder="Name">
						  	</div>
						  	<div class="form-group col-6">
						  		<label for="inputTime"> Timetables</label>
						  		<input type="time" class="form-control" id="inputTime" placeholder="Timetables">
						  	</div>
						  	<div class="form-group col-6">
						  		<label for="inputEmail"> Email</label>
						  		<input type="email" class="form-control" id="inputEmail" placeholder="Email">
						  	</div>
						  	<div class="form-group col-6">
						  		<label for="inputNumber"> Number of Guests</label>
						  		<input type="number" class="form-control" id="inputNumber" placeholder="Number of Guests">
						  	</div>
						  	<div class="form-group col-6">
						  		<label for="inputCel"> Phone</label>
						  		<input type="tel" class="form-control" id="inputCel" placeholder="Phone">
						  	</div>
  							<div class="form-group col-12">
  								<label for="inputComment"> Further requests</label>
								<textarea class="form-control" rows="4" id="inputComment" placeholder="Further requests"></textarea>
							</div>
					 	</div>
						<div class="row">
					  		<div class="col-md-4 col-md-offset-4">
					  			<button type="submit" class="btn btn-secondary btn-block">Reserve</button>
					  		</div>
					  	</div>
					</form>
				</div>
			</div>
			<!--- End of Reserve -->
			
			<div class="row footer bg-light">
				<div class="col">
					<p class="text-center">Follow us: <a class="social-icon" href="https://www.facebook.com/rubiktechnologiesShpk/"><i class="fab fa-facebook"></i></a> <a class="social-icon" href="https://www.instagram.com/rubiktechnologies/"><i class="fab fa-instagram"></i></a></p>
				</div>
				<div class="col">
					<p class="text-center">Copyright &copy; 2018</p>
				</div>
				<div class="col">
					<p class="text-center">Powered by: <a href="https://rubik-technologies.com/">Rubik Technologies</a></p>
				</div>
			</div>
		</div>
		<footer class="container">
			<div class= "row only-mobile">
				<div class="col-6">
					<a class="btn btn-primary btn-block text-center" href="tel:++390000000"><i class="fa fa-phone" aria-hidden="true"></i> Call</a>
				</div>
				<div class="col-6">
					<a class="btn btn-success btn-block text-center" href="https://api.whatsapp.com/send?phone=+390000000"><i class="fab fa-whatsapp" aria-hidden="true"></i> Whatsapp</a>
				</div>
			</div>
		</footer>
		